version: "3"
services:
  app:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service_account.json
      - PORT=8080
      - FLASK_DEBUG=True
    volumes:
      - .:/app
    ports:
      - "8080:8080"
