name: Delivery

on:
  push:
    branches:
      - main

env:
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/covid19-status-of-medical-care-provision-in-japan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: gcp auth
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: configure docker
        run: gcloud auth configure-docker --quiet
      - name: build image
        run: docker build . -t $IMAGE:${{ steps.vars.outputs.sha_short }}
      - name: push image
        run: docker push $IMAGE:${{ steps.vars.outputs.sha_short }}
      - name: deploy
        run: gcloud run deploy \
               --project ${{ secrets.GCP_PROJECT_ID }} \
               --image $IMAGE:${{ steps.vars.outputs.sha_short }} \
               --region asia-northeast1 \
               --platform managed \
               --concurrency 1 \
               --max-instances 1 \
               --update-env-vars SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }} \
               --quiet \
               --service-account ${{ secrets.CLOUDRUN_SERVICE_ACCOUNT }} \
               ${{ secrets.CLOUDRUN_SERVICE_NAME }}
